CREATE TABLE ADMISTRADOR(
	ADMIN_ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL UNIQUE,
	CONTRASENA VARCHAR(200) NOT NULL,
	MAIL VARCHAR(100) NOT NULL UNIQUE,
	CAMPO_V01 VARCHAR(100),
	CAMPO_N01 VARCHAR(100)
);


CREATE TABLE USUARIO (
	CEDULA VARCHAR(10) PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100)NOT NULL,
	MAIL VARCHAR(100) NOT NULL UNIQUE,
	QR VARBINARY(MAX),
	SALDO DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	FECHA_REGIST DATETIME NOT NULL DEFAULT GETDATE(),
	CAMPO_V01 VARCHAR(100),
	CAMPO_N01 VARCHAR(100)
);

CREATE TABLE RUTA(
	RUTA_ID INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_RUTA VARCHAR(100) NOT NULL,
	COSTO DECIMAL(10, 2) NOT NULL,
	CAMPO_V01 VARCHAR(100),
	CAMPO_N01 VARCHAR(100)
);

CREATE TABLE ESTACION (
    ESTACION_ID INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE_ESTACION VARCHAR(100) NOT NULL,
    Orden INT NOT NULL,
	RUTA_ID INT NOT NULL FOREIGN KEY REFERENCES RUTA(RUTA_ID),
	CAMPO_V01 VARCHAR(100),
	CAMPO_N01 VARCHAR(100)
);

CREATE TABLE TRANSACCION(
	TRANSACCION_ID INT IDENTITY (1,1) PRIMARY KEY,
	TIPO VARCHAR(8) CHECK (TIPO IN('Recarga', 'Gasto')) NOT NULL,
	MONTO DECIMAL(10,2) NOT NULL,
	FECHA_HORA DATETIME NOT NULL DEFAULT GETDATE(),
	CEDULA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES USUARIO(CEDULA),
	CAMPO_V01 VARCHAR(100),
	CAMPO_N01 VARCHAR(100)
);

CREATE TABLE VIAJE(
	VIAJE_ID INT PRIMARY KEY IDENTITY(1,1),
	FECHA_HORA DATETIME DEFAULT GETDATE(),
	COSTO DECIMAL(10, 2) NOT NULL,
	CEDULA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES USUARIO(CEDULA),
	RUTA_ID INT NOT NULL FOREIGN KEY REFERENCES RUTA(RUTA_ID),
	ESTACION_INICIO INT NOT NULL FOREIGN KEY REFERENCES ESTACION(ESTACION_ID),
	ESTACION_FIN INT NOT NULL FOREIGN KEY REFERENCES ESTACION(ESTACION_ID),
	CAMPO_V01 VARCHAR(100),
	CAMPO_N01 VARCHAR(100)
);

CREATE TABLE NOTIFICACION(
	NOTIFICACION_ID INT IDENTITY(1,1) PRIMARY KEY,
	TIPO_NOTI VARCHAR(100) NOT NULL,
	MENSAJE TEXT NOT NULL,
	FECHA_ENVIO DATETIME NOT NULL DEFAULT GETDATE(),
	ESTADO CHAR(8) CHECK (ESTADO IN('Enviado', 'Pendiente')) NOT NULL DEFAULT 'Pendiente',
	CEDULA VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES USUARIO(CEDULA),
	CAMPO_V01 VARCHAR(100),
	CAMPO_N01 VARCHAR(100)
);

select * from NOTIFICACION